name: landart
description: A featureful API wrapper for Lanyard & Lanyard KV written in Dart.
version: 1.2.0
homepage: https://github.com/NightFeather0615/landart
repository: https://github.com/NightFeather0615/landart
issue_tracker: https://github.com/NightFeather0615/landart/issues
topics: 
  - discord
  - lanyard

environment:
  sdk: '^3.0.0'

dependencies:
  http: ^1.1.2
  archive: ^3.4.9
  web_socket_channel: ^2.4.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
